### ISSUE TITLE
Fails randomly on different modules

### ISSUE THREAD

**Issue by VladislavKoldobskiy** [buildcenter/WindowsBuilder#1]
When I try building just the sample configuration, I am getting the following on different modules:

`[0723:54] Error: C:\WindowsBuilder\tools\Builder\Builder.psm1:357 char:25 +                         Die $_ 'InvokeTaskError' -NoWill +                         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ [<<==>>] Exception: Cannot bind argument to parameter "Message" because it is an empty string.
`
I sort of worked around this by disabling most of the modules (tts, unprotect, lockscreen, wallpaper, etc.), but it still fails with driver injection (which is included in my other .bsd file).
What could be the issue here? Error message gives me no hints at all.

**Comment by imacks** [comment]
There is currently an issue with error propagation that is being worked at. Meanwhile, you can look at the output to identify the failing module. Do you have the output?

Your resource folder may also lack the files specified in your bsd file, so a dir -Recurse of your directory structure will also help.

**Comment by imacks** [comment]
did it work? Closing this for now. Feel free to open up a new issue if you need more help.
