### ISSUE TITLE
assert statement checks wrong property

### ISSUE THREAD

**Issue by cschneegans** [buildcenter/WindowsBuilder#5]
**src/Package/Install.ps1** contains this statement:

`task Precheck {`
`    assert ($BuildEnv.themeColor) "The themeColor entry is empty or undefined."`

It appears this statement has been copied from **src/ThemeColor/Install.ps1** and has not been adopted properly. The assert statement should obviously reference the `$BuildEnv.package` property.

**Comment by imacks** [comment]
tks for reporting. omg the shame!!!
